### ISSUE TITLE
Howto guide (specifically the Dune version) not working in Safari

### ISSUE THREAD

**Issue by frou** [dbuenzli/brr#9] opened 2020-12-10 20:49 UTC
https://erratique.ch/software/brr/doc/web_page_howto.html

The basic instructions result in a working page.

But following the instructions that use Dune results in a blank page with JS that throws:

<img width="594" alt="Screenshot 2020-12-10 at 20 30 10" src="https://user-images.githubusercontent.com/172663/101826729-502fb800-3b27-11eb-99e6-f9bf603a2d9c.png">

I didn't do the OCaml Console parts with either.

---

brr 0.0.1
js_of_ocaml 3.8.0
dune 2.7.1
Safari 14.0.1

**Comment by dbuenzli** [comment] 2020-12-10 21:28
That's a bit odd I can reproduce with jsoo 3.7.1, but only in Safari, it works both in FF and Chrome. I'm afraid I don't have the time to look into this right now.

**Comment by frou** [comment] 2020-12-10 21:49
No worries. I'll mess around with it a bit more  probably

**Comment by dbuenzli** [comment] 2020-12-11 10:11
Okay I'll just /cc @hhugo in case that rings an obvious bell. 

I tested the [steps](https://erratique.ch/software/brr/doc/web_page_howto.html#quick) without `dune` and indeed it works. 

They also work if you invoke `dune` with `dune build --profile=release @app` which disables separate compilation. It's likely a `dune` issue the questions are: 

1. Is that an issue with our [dune instructions](https://erratique.ch/software/brr/doc/web_page_howto.html#dune_quick). 
2. Is that an issue with `dune`'s separate compilation
3. Why is the issue present only on `Safari`

**Comment by dbuenzli** [comment] 2021-02-04 13:49
> * Is that an issue with our [dune instructions](https://erratique.ch/software/brr/doc/web_page_howto.html#dune_quick) ?
> * Is that an issue with `dune`'s separate compilation ?

I think the answer to these questions is negative. 

At least I was able to reproduce that with non-`dune` separate jsoo build logic a few week ago but didn't have to time to pin down things precisely. 

Likely a Safari specific bug for `jsoo`.

**Comment by dbuenzli** [comment] 2021-09-19 21:54
Okay so the culprit *is* Brr 😬. With the latest jsoo (3.10.0), dune (2.8.5) and Safari (14.1.2),  I'm getting a precise stack trace.

It points to [this line](https://github.com/dbuenzli/brr/blob/b074832ae363ff9f68d52a2db31b3a83a94ee445/src/brr_canvas.ml#L1654). The problem is that `WebGL2RenderingContext` doesn't exist in Safari (it will be part of Safari 15). So we are looking up `undefined`. 

If you compile with separate compilation (`--profile=dev`) the lines don't get dead-coded away and thus error our [hello world](https://erratique.ch/software/brr/doc/web_page_howto.html#quick) explodes. Without separate compilation `--profile=release` this gets dead-coded away and thus the program runs without problem. 
 
I think I will simply stub the values with `0` if `WebGL2RenderingContext` context is null. Pages will need to first try to get a GL2 context before using these values which will fail before they try to use the `0` if it's unsupported.

However I'm a bit suprised by this behaviour. I thought that with separate compilation `js_of_ocaml` would still dead code away whole compilation units that are unused. Our hello world just uses `brr.cmo` of `brr.cma`, not `brr_canvas.cmo`.

@hhugo is that expected behaviour ?

**Closed** 2021-09-19 22:24 UTC
Labels: bug

**Comment by hhugo** [comment] 2021-09-20 06:26
In separate compilation, jsoo only does deadcode elimination within compilation units. Here, you would need https://github.com/ocsigen/js_of_ocaml/issues/943

**Comment by dbuenzli** [comment] 2021-09-20 09:52
Aha, thanks. Yes, would be nice to have, if only for least surprise w.r.t. regular OCaml compilers.

I could separate `brr`'s [toplevel compilation units](https://github.com/dbuenzli/brr/blob/5d59f62555d505af37d1e9aa2437cfa31b0fd9b5/src/brr.mllib) into separate libraries but it feels a bit artificial (and rather unconvenient for users).
